// courseData.js
import courseImg from "../Assests/coursesimg00.png";
import aboutImg00 from "../Assests/aboutimg00.png";
import aboutImg01 from "../Assests/aboutimg01.png";
import aboutImg02 from "../Assests/aboutimg02.png";
import aboutImg03 from "../Assests/aboutimg03.png";

// Just cycle through images to make variety
const images = [courseImg, aboutImg00, aboutImg01, aboutImg02, aboutImg03];

const courseData = {
  ALL: [
    {
      id: 1,
      title: "Level 3 Diploma in Aesthetics",
      desc: "Comprehensive foundation in advanced skin care.",
      price: 380,
      oldPrice: 500,
      rating: 4.5,
      img: images[0],
    },
    {
      id: 2,
      title: "Certificate in Beauty Therapy",
      desc: "Hands-on training for salon professionals.",
      price: 250,
      oldPrice: 320,
      rating: 4.2,
      img: images[1],
    },
    {
      id: 3,
      title: "Level 5 Diploma in Education",
      desc: "Learn teaching strategies for adult learners.",
      price: 450,
      oldPrice: 600,
      rating: 4.7,
      img: images[2],
    },
    {
      id: 4,
      title: "Diploma in Digital Marketing",
      desc: "Practical skills for online campaigns & SEO.",
      price: 300,
      oldPrice: 400,
      rating: 4.3,
      img: images[3],
    },
     {
      id: 4,
      title: "Diploma in Digital Marketing",
      desc: "Practical skills for online campaigns & SEO.",
      price: 300,
      oldPrice: 400,
      rating: 4.3,
      img: images[3],
    },
    
  ],

  QUALIFI: [
    {
      id: 1,
      title: "Qualifi Level 7 Diploma in Strategic Management",
      desc: "Gain insights into strategic leadership & decision making.",
      price: 600,
      oldPrice: 750,
      rating: 4.8,
      img: images[4],
    },
    {
      id: 2,
      title: "Qualifi Certificate in Business Innovation",
      desc: "Learn modern business tools & startup methodologies.",
      price: 400,
      oldPrice: 550,
      rating: 4.4,
      img: images[0],
    },
    {
      id: 4,
      title: "Qualifi Diploma in Human Resource Management",
      desc: "Manage recruitment, training and workplace performance.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[1],
    },
    {
      id: 5,
      title: "Qualifi Diploma in Human Resource Management",
      desc: "Manage recruitment, training and workplace performance.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[1],
    },
    {
      id: 6,
      title: "Qualifi Certificate in Finance",
      desc: "Understand corporate finance and accounting basics.",
      price: 450,
      oldPrice: 600,
      rating: 4.2,
      img: images[2],
    },
    {
      id: 7,
      title: "VTCT Level 3 Diploma in Hairdressing",
      desc: "Professional hairdressing skills with salon exposure.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[3],
    },
  ],

  VTCT: [
    {
      id: 1,
      title: "VTCT Level 3 Diploma in Hairdressing",
      desc: "Professional hairdressing skills with salon exposure.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[3],
    },
    {
      id: 2,
      title: "VTCT Level 2 Award in Beauty Therapy",
      desc: "Entry-level course for aspiring beauticians.",
      price: 220,
      oldPrice: 300,
      rating: 4.3,
      img: images[4],
    },
    {
      id: 3,
      title: "VTCT Level 4 Certificate in Advanced Skincare",
      desc: "Specialized skincare treatments and facial procedures.",
      price: 350,
      oldPrice: 500,
      rating: 4.4,
      img: images[0],
    },
    {
      id: 4,
      title: "VTCT Level 5 Diploma in Salon Management",
      desc: "Learn how to manage and grow a beauty business.",
      price: 420,
      oldPrice: 550,
      rating: 4.5,
      img: images[1],
    },
    {
      id: 5,
      title: "Qualifi Diploma in Human Resource Management",
      desc: "Manage recruitment, training and workplace performance.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[1],
    },
    {
      id: 6,
      title: "Qualifi Certificate in Finance",
      desc: "Understand corporate finance and accounting basics.",
      price: 450,
      oldPrice: 600,
      rating: 4.2,
      img: images[2],
    },
  ],

  PERSONS: [
    {
      id: 1,
      title: "First Aid Training for Professionals",
      desc: "Essential first aid techniques for workplace safety.",
      price: 180,
      oldPrice: 250,
      rating: 4.5,
      img: images[2],
    },
    {
      id: 2,
      title: "Fire Safety Awareness",
      desc: "Learn fire safety protocols and prevention measures.",
      price: 150,
      oldPrice: 200,
      rating: 4.1,
      img: images[3],
    },
    {
      id: 3,
      title: "Health & Safety in the Workplace",
      desc: "Basic compliance and occupational safety training.",
      price: 200,
      oldPrice: 280,
      rating: 4.2,
      img: images[4],
    },
    {
      id: 4,
      title: "Emergency Evacuation Training",
      desc: "Evacuation drills and crisis management essentials.",
      price: 170,
      oldPrice: 230,
      rating: 4.0,
      img: images[0],
    },
    {
      id: 5,
      title: "Qualifi Diploma in Human Resource Management",
      desc: "Manage recruitment, training and workplace performance.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[1],
    },
    {
      id: 6,
      title: "Qualifi Certificate in Finance",
      desc: "Understand corporate finance and accounting basics.",
      price: 450,
      oldPrice: 600,
      rating: 4.2,
      img: images[2],
    },
  ],

  "PRO QUAL": [
    {
      id: 1,
      title: "Professional Diploma in Project Management",
      desc: "Tools & techniques to manage real-world projects.",
      price: 700,
      oldPrice: 900,
      rating: 4.9,
      img: images[1],
    },
    {
      id: 2,
      title: "Pro Qual Certificate in Leadership",
      desc: "Develop leadership skills for modern organizations.",
      price: 480,
      oldPrice: 600,
      rating: 4.5,
      img: images[2],
    },
    {
      id: 3,
      title: "Professional Award in Data Analysis",
      desc: "Practical approach to handling and analyzing data.",
      price: 400,
      oldPrice: 520,
      rating: 4.4,
      img: images[3],
    },
    {
      id: 4,
      title: "Pro Qual Diploma in Supply Chain",
      desc: "Learn logistics, procurement & supply chain management.",
      price: 600,
      oldPrice: 750,
      rating: 4.7,
      img: images[4],
    },
  ],

  SQA: [
    {
      id: 1,
      title: "SQA Diploma in Business Studies",
      desc: "Understand business fundamentals with real-life examples.",
      price: 350,
      oldPrice: 500,
      rating: 4.3,
      img: images[0],
    },
    {
      id: 2,
      title: "SQA Certificate in IT Systems",
      desc: "Basics of IT infrastructure, systems and networking.",
      price: 420,
      oldPrice: 550,
      rating: 4.5,
      img: images[1],
    },
    {
      id: 3,
      title: "SQA Award in Communication",
      desc: "Improve your professional and workplace communication.",
      price: 280,
      oldPrice: 350,
      rating: 4.2,
      img: images[2],
    },
    {
      id: 4,
      title: "SQA Certificate in Digital Applications",
      desc: "Introduction to office and business applications.",
      price: 300,
      oldPrice: 400,
      rating: 4.1,
      img: images[3],
    },
    {
      id: 5,
      title: "Qualifi Diploma in Human Resource Management",
      desc: "Manage recruitment, training and workplace performance.",
      price: 500,
      oldPrice: 650,
      rating: 4.6,
      img: images[1],
    },
    {
      id: 6,
      title: "Qualifi Certificate in Finance",
      desc: "Understand corporate finance and accounting basics.",
      price: 450,
      oldPrice: 600,
      rating: 4.2,
      img: images[2],
    },
  ],

  ICQ: [
    {
      id: 1,
      title: "ICQ Certificate in Health & Social Care",
      desc: "Prepare for a rewarding career in social services.",
      price: 280,
      oldPrice: 350,
      rating: 4.4,
      img: images[4],
    },
    {
      id: 2,
      title: "ICQ Diploma in Customer Service",
      desc: "Customer care principles for retail & hospitality.",
      price: 300,
      oldPrice: 420,
      rating: 4.3,
      img: images[0],
    },
    {
      id: 3,
      title: "ICQ Certificate in Team Leading",
      desc: "Develop team management and leadership skills.",
      price: 350,
      oldPrice: 500,
      rating: 4.5,
      img: images[1],
    },
    {
      id: 4,
      title: "ICQ Diploma in Marketing",
      desc: "Marketing fundamentals with practical case studies.",
      price: 400,
      oldPrice: 550,
      rating: 4.6,
      img: images[2],
    },
  ],
};

export default courseData;
